version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env  # This loads the environment variables from .env file
    volumes:
      - ./backend:/app  # Mount the backend directory for hot reloading
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload  # Enable hot reloading
    networks:
      - appnet

  frontend:
    build: ./frontend
    ports:
      - "3005:3005"  # Changed to match the dev server port
    volumes:
      - ./frontend:/app  # Mount the frontend directory for hot reloading
      - /app/node_modules  # Preserve node_modules in container
    working_dir: /app
    command: npm run dev
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
