version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env  # This loads the environment variables from .env file
    volumes:
      - ./backend:/app  # Mount the backend directory for hot reloading
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload  # Enable hot reloading
    networks:
      - appnet

  frontend:
    build: ./frontend
    ports:
      - "3005:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
